export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',

  CONFIRMED = 'CONFIRMED',
  PRODUCTION_TICKET_CREATED = 'PRODUCTION_TICKET_CREATED',
  FABRIC_CUTTING = 'FABRIC_CUTTING',
  SEWING = 'SEWING',
  QUALITY_CHECK = 'QUALITY_CHECK',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',

  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}